### ISSUE TITLE
Dependencies without versioning

### ISSUE THREAD

**Issue by worroc** [Yelp/swagger_spec_validator#116]
Project Dependencies mentioned in setup.py doesn't contain their versions and denies to pin the version of the swagger_spec_validator itself.

 setup.py
...
    install_requires=[
        'jsonschema',
        'pyyaml',
        'six',
    ],

In my project I pin the version of swagger-spec-validator to 2.0.2
suddenly I started to get an error:

swagger_spec_validator.common.SwaggerValidationError: module 'jsonschema._validators' has no attribute 'properties_draft4'

the docker install log shows that the reason is a version of jsonschema

pip install:
Collecting jsonschema (from swagger-spec-validator==2.0.2->-r /requirements.txt (line 5))
Downloading https://files.pythonhosted.org/packages/cd/e6/be1b2a6ebebdaf1f790f1e750bb720fbda0335c2a19601ea9d8bb5059f38/jsonschema-3.0.0-py2

the version swagger_spec_validator==2.0.2 work perfectly with jsonschema==2.6.0 but not with 3.0.0

**Comment by macisamuele** [comment]
@worroc thanks a lot for the reporting.
Some time ago I did address the concern related to jsonschema-validator v3.0.0 release (https://github.com/Yelp/swagger_spec_validator/pull/103).
The latest version does work properly with v3.0.0 too so I would recommend to bump `swagger-spec-validator`

**Comment by macisamuele** [comment]
@worroc I'm going to close it for now. Free free to re-open it in case bump-ing swagger-spec-validator does not help you out.
